name: Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate version number
        shell: pwsh
        run: |
          $csprojContent = Get-Content -Path "./SurgingCloud.Cli/SurgingCloud.Cli.csproj" -Raw
          $versionMatch = [regex]::Match($csprojContent, '<Version>([^<]+)</Version>')
          $CS_VERSION = $versionMatch.Groups[1].Value
          
          $TAG = $env:GITHUB_REF -replace '^refs/(tags|heads)/',''
          
          if ($CS_VERSION -ne $TAG) {
            Write-Output "::error::Tag mismatch! Run tag: $TAG, .csproj version: $CS_VERSION"
            exit 1
          }
        
          Write-Output "Validation succeeds, version number = $TAG"
